[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "sensorx"
version = "1.0.0"

[project.scripts]
boot = "sensortx.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]